### ISSUE TITLE
Reverse sides for bot bubbles and my bubbles

### ISSUE THREAD

**Issue by brianlovin** [SaraVieira/boredaf.app#8]
Most chat apps have your bubbles on the right side and the other person on the left side; in this case it's reversed so it feels like I've sent the messages that the bot has sent. Do you think these should be swapped?

**Comment by elizabetdev** [comment]
Hi @brianlovin,
You're not the first person complaining about this! 😛 

 I think you're right we should swap it! 

Thanks!

**Comment by frextrite** [comment]
Was I the [first](https://github.com/SaraVieira/boredaf.app/issues/7)? XD

**Comment by brianlovin** [comment]
@miukimiu sorry if I came across as complaining! Glad to see it land though :)
